
package login_form;

import java.awt.*;
import java.awt.event.*;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.beans.PropertyChangeEvent;
import java.beans.PropertyChangeListener;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.*;
import javax.swing.GroupLayout;
import javax.swing.JButton;
import javax.swing.JDialog;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.LayoutStyle;
import javax.swing.event.ChangeEvent;
import javax.swing.event.ChangeListener;



/**
 *
 * @author thomasongwae
 */
public class login_page extends javax.swing.JFrame {

    /**
     * Creates new form login_page
     */
    public  login_page()
    {   
        
         
          initComponents();
          iconadditiontoframe();
          displayloginpagepicture();
          
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jPasswordField1 = new javax.swing.JPasswordField();
        jCheckBox1 = new javax.swing.JCheckBox();
        jButton3 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Admin log in");
        setLocation(new java.awt.Point(0, 0));
        setMinimumSize(new java.awt.Dimension(560, 430));
        setPreferredSize(new java.awt.Dimension(560, 430));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Abhaya Libre", 0, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("   Login  Page [Friends With Unique Purpose]");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 12, 528, -1));

        jLabel2.setFont(new java.awt.Font("Noto Sans", 0, 14)); // NOI18N
        jLabel2.setText("UserName ");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 240, -1, -1));

        jTextField1.setText("username");
        jTextField1.setToolTipText("");
        jTextField1.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                jTextField1InputMethodTextChanged(evt);
            }
        });
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 230, 275, 41));

        jLabel3.setFont(new java.awt.Font("Noto Sans", 0, 14)); // NOI18N
        jLabel3.setText("PassWord");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 280, 119, 46));

        jButton1.setText("Login Now");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 350, 112, -1));

        jButton2.setText("Reset Password");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 350, -1, -1));

        jPasswordField1.setText("password");
        jPasswordField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordField1ActionPerformed(evt);
            }
        });
        getContentPane().add(jPasswordField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 280, 275, 46));

        jCheckBox1.setText("Remember me");
        jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox1ActionPerformed(evt);
            }
        });
        getContentPane().add(jCheckBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 350, 120, 41));

        jButton3.setText("Exit");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 350, 109, -1));

        jLabel4.setText("                      Picture HERE");
        jLabel4.setBorder(null);
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 50, 210, 160));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    public void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
         
        //System.out.println("Login Button pressed successfully");
         String textFieldValue = jTextField1.getText();
          String passwordfield =jPasswordField1.getText();
             
        Connection conn = null;
        Statement stmt = null;
               
               
        try {
            Class.forName("org.sqlite.JDBC");
        
            conn = DriverManager.getConnection("jdbc:sqlite:login_form.db");
            
                    
             
              stmt = conn.createStatement();
              
              String sql = "SELECT * FROM admin";
              
              
            
             var result = stmt.executeQuery(sql);  
              
             
              while (result.next()) 
              {
                
                 
                       
                if (textFieldValue.equals(result.getString("username")) && passwordfield.equals(result.getString("password"))) 
         
                   {
              
                              
                            JFrame frameone = new JFrame();
                            //changing the jframe icon 
                            Image icon = Toolkit.getDefaultToolkit().getImage("/mnt/sda7/java_programming/login_form/src/login_form/login_successfully_drawing.png");
                            frameone.setIconImage(icon);
                       
                       
                       
                             
          
                 int options1 = JOptionPane.showConfirmDialog(frameone,"Hello " +textFieldValue+ " Login was Successfully","Successfull", JOptionPane.YES_NO_OPTION);
                           
                            if (options1 == JOptionPane.YES_OPTION)
                            {
                                
                                dispose();
             
           
                   
                              // close connection to a database
                                result.close();
                                stmt.close();
                                conn.close();
              
              
                
                                  home_page page = new home_page();  
                                  page.setVisible(true);  
                                
                            }
                            
                            if (options1 == JOptionPane.NO_OPTION)
                            {
                                //close Database connections
                                result.close();
                                stmt.close();
                                conn.close();
                                
                                String st = "";
                                jTextField1.setText(st);
                                
                                jPasswordField1.setText(st);
                                
                                
                            }
          
            
                            }
          
                       else 
                            {   
              
              
                       
                         result.close();
                         stmt.close();
                         conn.close();
                         
                         
                           JFrame frameone1 = new JFrame();
                            //changing the jframe icon 
                            Image icon1 = Toolkit.getDefaultToolkit().getImage("/mnt/sda7/java_programming/login_form/src/login_form/login_unsuccessfully_drawing.png");
                            frameone1.setIconImage(icon1);
                         
                         
                          JOptionPane.showMessageDialog(frameone1, "Not Successfully");
                           
                          
              
                 }
                 
          
                 
              }
            
             
          
               
        }
        catch (ClassNotFoundException ex) 
        {
            Logger.getLogger(login_page.class.getName()).log(Level.SEVERE, null, ex);
        } 
        catch (SQLException ex)
        {  
            Logger.getLogger(login_page.class.getName()).log(Level.SEVERE, null, ex);
        }
               
     
          
    }//GEN-LAST:event_jButton1ActionPerformed
    
    public void jTextField1ActionPerformed(java.awt.event.ActionEvent evt)
    {//GEN-FIRST:event_jTextField1ActionPerformed
        
        String textFieldValue = jTextField1.getText();
         
    }//GEN-LAST:event_jTextField1ActionPerformed

    public void jPasswordField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordField1ActionPerformed
           
              
        String passwordfield =jPasswordField1.getText();
              
    }//GEN-LAST:event_jPasswordField1ActionPerformed

    public void jTextField1InputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_jTextField1InputMethodTextChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1InputMethodTextChanged

    public void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
       
          JOptionPane.showMessageDialog(null, "Not yet Working, contact admin");
        
    }//GEN-LAST:event_jButton2ActionPerformed

    public void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1ActionPerformed
        
    }//GEN-LAST:event_jCheckBox1ActionPerformed

    public void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
       
         
       
        home_page_exit_button Exiting = new home_page_exit_button();
        
        Exiting.exit_home_button();
        
         
       
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("GTK+".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(login_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(login_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(login_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(login_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new login_page().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables

   
    
    private void   iconadditiontoframe()
            
    {
         //set the frame Icon to my customized ICON
          Image icon = Toolkit.getDefaultToolkit().getImage("/mnt/sda7/java_programming/login_form/src/login_form/login_page_corner_drawing.png");
          setIconImage(icon);
       
    }
    
    
    private void  displayloginpagepicture()
            
    {
        
        
      ImageIcon ii = new ImageIcon("/mnt/sda7/java_programming/login_form/src/login_form/login_page_Friends_drawing.png");
                          
      //Resize image to fit jlabel.
      Image img = ii.getImage().getScaledInstance(jLabel4.getWidth(), jLabel4.getHeight(), Image.SCALE_SMOOTH);
      
      
      jLabel4.setIcon(new ImageIcon(img));
        
        
    }
    
    
    }

