
package login_form;


import java.awt.Container;
import java.awt.EventQueue;
import java.awt.Image;
import java.awt.Toolkit;
import java.awt.image.BufferedImage;
import java.io.ByteArrayOutputStream;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.io.InputStream;
import javax.imageio.ImageIO;
import javax.swing.GroupLayout;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JComponent;
import javax.swing.JFileChooser;
import javax.swing.JLabel;
import javax.swing.filechooser.FileSystemView;  
import java.sql.Connection;  
import java.sql.DriverManager;  
import java.sql.SQLException; 
import java.util.logging.Level;
import java.util.logging.Logger;
import java.sql.*;
import java.sql.PreparedStatement;  
import javax.swing.DefaultListModel;
import javax.swing.JFrame;
import javax.swing.JList;
import javax.swing.JOptionPane;
import javax.swing.event.ListSelectionListener;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author thomasongwae
 */
public class register_form extends javax.swing.JFrame {

    /**
     * Creates new form register_form
     */
 
    
    
    
     
    
    
    public register_form() 
    {   
        
        initComponents();
        additingimagetojframeicon();
        
        
        
        
    
        
   
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Registration Form");
        setMinimumSize(new java.awt.Dimension(757, 400));
        setPreferredSize(new java.awt.Dimension(757, 400));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Noto Sans", 0, 14)); // NOI18N
        jLabel1.setText("First Name");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, 83, 39));

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 60, 140, 40));

        jLabel2.setFont(new java.awt.Font("Noto Sans", 0, 14)); // NOI18N
        jLabel2.setText("Mobile Number");
        jLabel2.setMaximumSize(new java.awt.Dimension(68, 20));
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 110, 40));

        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(132, 120, 320, 48));

        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setFont(new java.awt.Font("Noto Sans", 0, 14)); // NOI18N
        jRadioButton1.setText("Male");
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jRadioButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 260, -1, 37));

        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setFont(new java.awt.Font("Noto Sans", 0, 14)); // NOI18N
        jRadioButton2.setText("Female");
        jRadioButton2.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jRadioButton2StateChanged(evt);
            }
        });
        jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jRadioButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 260, -1, 37));

        jLabel3.setFont(new java.awt.Font("Noto Sans", 0, 14)); // NOI18N
        jLabel3.setText("Gender");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 270, 79, -1));

        jLabel5.setFont(new java.awt.Font("Noto Sans", 0, 14)); // NOI18N
        jLabel5.setText("ID Number");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, 103, 47));

        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 190, 320, 47));

        jButton1.setBackground(new java.awt.Color(61, 99, 136));
        jButton1.setFont(new java.awt.Font("Noto Sans", 0, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 0, 57));
        jButton1.setText("Submit");
        jButton1.setPreferredSize(new java.awt.Dimension(78, 42));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 320, -1, -1));

        jButton3.setFont(new java.awt.Font("Noto Sans", 0, 14)); // NOI18N
        jButton3.setText("Add Picture");
        jButton3.setMaximumSize(new java.awt.Dimension(70, 35));
        jButton3.setMinimumSize(new java.awt.Dimension(70, 42));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 320, -1, -1));

        jButton4.setFont(new java.awt.Font("Noto Sans", 0, 14)); // NOI18N
        jButton4.setText("Exit");
        jButton4.setMaximumSize(new java.awt.Dimension(70, 42));
        jButton4.setMinimumSize(new java.awt.Dimension(70, 42));
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 320, 79, -1));

        jLabel4.setFont(new java.awt.Font("Noto Sans", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(241, 13, 50));
        jLabel4.setText("                 No Photo Selected");
        jLabel4.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 10, 280, 290));

        jLabel6.setText("Middle Name");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 20, -1, -1));

        jTextField5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField5ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 120, 40));

        jLabel7.setText("Last Name/Others");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 20, -1, -1));

        jTextField6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField6ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField6, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 60, 120, 40));

        jButton2.setText("Other Options");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 320, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    public void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
          //System.out.println("ID number");
          String textFieldValue4 = jTextField3.getText();
          //System.out.println(textFieldValue4);
    }//GEN-LAST:event_jTextField3ActionPerformed

    public void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        
        
        SubmitButtonToDataseRegister();
        
        
      
    }//GEN-LAST:event_jButton1ActionPerformed

    public void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
         //System.out.println("Full name text area");
         String textFieldValue = jTextField1.getText();
         //System.out.println(textFieldValue);
          
       
    }//GEN-LAST:event_jTextField1ActionPerformed

    public void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
          //System.out.println("Mobile phone Number");
          String textFieldValue2 = jTextField2.getText();
         //System.out.println(textFieldValue2);
    }//GEN-LAST:event_jTextField2ActionPerformed

    public void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
      
        
        jRadioButton1.isSelected();
           
              
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    public void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton2ActionPerformed
        
         
            jRadioButton2.isSelected();
             //System.out.println("Female selected");
             
    }//GEN-LAST:event_jRadioButton2ActionPerformed

    public void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
                    
        
                     //System.out.println("Picture button selected");
            
                     JFileChooser fileChooser = new JFileChooser();
                     
                      //Only search for images with these extensions.

                  FileNameExtensionFilter fnwf = new FileNameExtensionFilter("PNG JPG AND JPEG", "png", "jpeg", "jpg");
                     fileChooser.addChoosableFileFilter(fnwf);
                     int load = fileChooser.showOpenDialog(null);
                     
                     //If open button has being clicked.
                     if (load == fileChooser.APPROVE_OPTION) 
                          {
                           //  File f = null;
                             f = fileChooser.getSelectedFile();
                             
                             
                           
                            path = f.getAbsolutePath();
                            
                             
                          ImageIcon ii = new ImageIcon(path);
                          
                          
                          //Resize image to fit jlabel.
                             Image img = ii.getImage().getScaledInstance(jLabel4.getWidth(), jLabel4.getHeight(), Image.SCALE_SMOOTH);
                             
                             
                             
                             
                             //display image on jpanel
                             jLabel4.setIcon(new ImageIcon(img));
                     
                             
                             try
                             {
                                 
                             File image=new File(path);
                             
                            
                             
                             FileInputStream fis=new FileInputStream(image);
                             
                              ByteArrayOutputStream baos=new ByteArrayOutputStream();
                                 byte[] buf=new byte[1024];
                                 
                                 for(int readnum; (readnum=fis.read(buf)) !=-1;)
                                        {            
                                         baos.write(buf,0,readnum);                
                                       }
                           
                                  pimage = baos.toByteArray();
                             
                             }
                             
                             catch (FileNotFoundException ex) 
                             {
                             Logger.getLogger(register_form.class.getName()).log(Level.SEVERE, null, ex);
                            } catch (IOException ex)
                            {
                             Logger.getLogger(register_form.class.getName()).log(Level.SEVERE, null, ex);
                         }
                             
                                  
                     
                          }
                     
                          
                       
                     
                    
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
      
         dispose();
         //System.exit(0);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jRadioButton2StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jRadioButton2StateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton2StateChanged

    private void jTextField5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField5ActionPerformed

    private void jTextField6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField6ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        
        JOptionPane.showMessageDialog(null, "A future feature be patient");
        
        
    }//GEN-LAST:event_jButton2ActionPerformed

   
    
    
    
    public static void main(String args[]) 
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("GTK+".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(register_form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(register_form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(register_form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(register_form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() 
            {
                new register_form().setVisible(true);
              
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    // End of variables declaration//GEN-END:variables
    
    //making these varible global so that they can be accesed from anyway in the program
    
    File f = null;         
    String path = null; 
    byte[] pimage = null;
    
    
    
    
    private void clearingdatafromthejtextfield()
            
            
    {
        
        
         String def = "";
         
            jTextField5.setText(def);
            jTextField6.setText(def);
         
         
         
            jTextField1.setText(def);
                //System.out.println("Name cleared");
            jTextField2.setText(def);
                //System.out.println("Mobile cleared");
            jTextField3.setText(def);
                //System.out.println("ID cleared");
            
            jRadioButton1.setSelected(false);  
                //System.out.println("male selection cleared");
            jRadioButton2.setSelected(false);
                //System.out.println("Female selection cleared");
                    
            jLabel4.setIcon(null);
                 //System.out.println("Image cleared");
        
    }
    private void  additingimagetojframeicon()
            
    {
        
         //set the frame Icon to my customized ICON
          Image icon = Toolkit.getDefaultToolkit().getImage("/mnt/sda7/java_programming/login_form/src/login_form/register_page_corner_drawing.png");
          setIconImage(icon);
        
    }
   
   protected void SubmitButtonToDataseRegister()
           
           
   {
       
       
        //System.out.println("Submit button clicked");
        
        String textFieldFirstName = jTextField5.getText(); // first name
        String textFieldMiddleName = jTextField6.getText(); // Middle name
        String textFieldLastName = jTextField1.getText(); // Last name
                    
        
        String  allnamecollection = new String(textFieldFirstName +" "+ textFieldMiddleName +" "+ textFieldLastName);
                    
        var allnamecollectiontoupper = allnamecollection.toUpperCase();
         
          String   textFieldValue1 = new String(allnamecollectiontoupper); 
            
            
            
            
            
            
            
         String textFieldValue2 = jTextField2.getText(); //mobile
         String textFieldValue4 = jTextField3.getText(); //ID
        // String imageIcon = jLabel4.getText();
        
         
        
         
        // String  data1 ;
        String data1 = null;
        // String data1 = new String();
         
        
        //trying to prevent entering null name, id  number and phone number into the database
        
        if (textFieldFirstName.isEmpty() || textFieldValue2.isEmpty() || textFieldValue4.isEmpty())
        {
            
            
            
            
            WhenRegisterFormIsEmptyCatcher Catcher = new WhenRegisterFormIsEmptyCatcher();
            Catcher.WhenRegisterFormIsEmpty();
            
            
            
            
        } 
        
                
        else
        {
        
        //used two if two work with radiobutton , although it is not good programming but it worked !!!
         if (jRadioButton1.isSelected())
             
              {
             //jRadioButton1.isSelected(); //male selected
                data1 = "Male";
               } 
         
         if (jRadioButton2.isSelected())
         
             {
             jRadioButton2.isSelected();
             data1 = "Female";
             
             }
         
        
         Connection conn = null;
         
         PreparedStatement stmt = null;
         
       
        
        try 
           {
               
            Class.forName("org.sqlite.JDBC");
            conn = DriverManager.getConnection("jdbc:sqlite:login_form.db");
            
            //System.out.println("Opened database successfully");
              
             
            // //System.out.println("\nReady to commint data into database");
            conn.setAutoCommit(false);
           
            //stmt = conn.createStatement();
             
             
           String sql = ("INSERT INTO details (names,idnumber,mobile,gender,photo) VALUES('" + textFieldValue1 + "','" + textFieldValue4 + "','" + textFieldValue2 + "','" + data1 + "',?);");
               
        
        
            stmt=conn.prepareStatement(sql);
                   
            stmt.setBytes(1, pimage);
            stmt.execute();
                
                   conn.commit();
                   stmt.close();
                   conn.close();
             
             
            RegisterDataSavedToDatabase DataSaved = new RegisterDataSavedToDatabase();
            DataSaved.RegisterDataSavedSucess();
            
            
               
             //calling the methd to clear the field for new data entry.
             clearingdatafromthejtextfield();
            
            
            
         
        
              
           } 
           catch (ClassNotFoundException ex)
                  {
                       
                    } 
        catch (SQLException ex)
                {
                    
            
                 } 
        }
       
       
       
   }
   
}

        
